import { config } from 'dotenv';
config();

import '@/ai/flows/hmac-v4-config-generator.ts';
import '@/ai/flows/autonomous-compliance-monitor.ts';
import '@/ai/flows/ledger-audit-flow.ts';
import '@/ai/flows/sports-insight-flow.ts';
import '@/ai/flows/p2c-settlement-flow.ts';
import '@/ai/flows/integration-assistant-flow.ts';
import '@/ai/flows/protocol-architect-flow.ts';
import '@/ai/flows/investor-pitch-flow.ts';
import '@/ai/flows/merchant-onboarding-flow.ts';
import '@/ai/flows/merchant-performance-review-flow.ts';
import '@/ai/flows/liquidity-optimizer-flow.ts';
import '@/ai/flows/cross-chain-gateway-flow.ts';
import '@/ai/flows/identity-reputation-flow.ts';
import '@/ai/flows/governance-architect-flow.ts';
import '@/ai/flows/executive-execution-flow.ts';
import '@/ai/flows/inter-bank-settlement-flow.ts';
import '@/ai/flows/trade-arbitration-flow.ts';
import '@/ai/flows/imperial-oracle-flow.ts';
import '@/ai/flows/off-ramp-flow.ts';
import '@/ai/flows/alert-dispatcher-flow.ts';
import '@/ai/flows/imperial-query-flow.ts';
import '@/ai/flows/sovereign-legacy-flow.ts';
import '@/ai/flows/amex-on-demand-flow.ts';
import '@/ai/flows/amex-token-strategy-flow.ts';
import '@/ai/flows/neural-audit-flow.ts';
import '@/ai/flows/sovereign-grid-autonomy-flow.ts';
import '@/ai/flows/sovereign-vault-flow.ts';
import '@/ai/flows/data-lake-ingest-flow.ts';
